[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "net"
version = "0.1.0"
license = "MIT/Apache-2.0"

[dependencies]
bit_field = "0.7.0"
byteorder = { version = "1.0.0", default-features = false }

[features]
default = ["alloc"]
alloc = []
